//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cashierless_Checkout
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Barcode
    {
        public string barcode { get; set; }
        public short produceID { get; set; }
    
        public virtual TBL_Product TBL_Product { get; set; }
    }
}
