//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cashierless_Checkout.entity.old_sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Sales_History
    {
        public int id { get; set; }
        public short productID { get; set; }
        public string dateSales { get; set; }
    }
}
