//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cashierless_Checkout.entity.admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Admin
    {
        public byte id { get; set; }
        public string admin_nick { get; set; }
        public string admin_password { get; set; }
    }
}
